---
- name: create hpmepage and install of software packages  
  hosts: all
  become: true
  vars:
    - myMessage: "This is a simple webpage hosted on nginx"
  tasks: 
           
    - name: install software packages  
      yum:
        name: 
          - vim
          - nginx
          - git 
        state: present

    - name: start nginx server
      service:
        name: nginx
        state: started
      become: true
    
    - name: insert index page
      template: 
         src: ./nginx-files/index.html.j2
         dest: /usr/share/nginx/html/index.html

    # - name: copy nginx config file
    #   file:
    #     src: /nginx-files/nginx.conf
    #     dest: /etc/nginx/sites-available/default 
    #     state: link

    # - name: enable configuration
    #   file:
    #     dest: /etc/nginx/sites-enabled/default
    #     src: /etc/nginx/sites-available/default
    #     state: link

    # - name: index.html copy
    #   template:
    #     src: ./nginx-files/index.html.j2
    #     dest: /usr/share/nginx/html/index.html
    #     mode: 0644


    # - name: create www directory
    #   file:
    #     path: /var
    #     content: "hello welcome to the webpage"


      

