---
- name: create hpmepage and install of software packages  
  hosts: all
  become: true
  tasks:

    - name: debug module
      debug:
        

    # - name: latest package installs
    #   yum:
    #     name: vim
    #     state: latest

    # - name: start nginx server
    #   service:
    #     name: nginx
    #     state: started
    #   become: true

    # - name: add nginx config file
    #   copy:
    #     src: etc/nginx/nginx.conf
    #     #dest: /etc/nginx/nginx.conf
    #     content: "hello welcome to the webpage"


      

