---
- name: create hpmepage and install of software packages  
  hosts: all
  become: true
  tasks:        

    # - name: latest package installs
    #   yum:
    #     name:
    #       - vim
    #       - git
    #       - nginx
    #     state: latest

    - name: install git 
      yum:
        name: git
      state: latest

    # - name: start nginx server
    #   service:
    #     name: nginx
    #     state: started
    #   become: true

    # - name: add nginx config file
    #   copy:
    #     src: etc/nginx/nginx.conf
    #     dest: /etc/nginx/nginx.conf
    #     content: "hello welcome to the webpage"


      

