---
- name: create hpmepage and install of software packages  
  hosts: all
  become: true
  tasks: 
           
    - name: install nginx 
      yum:
        name: 
          - vim
          - nginx
          - git 
        state: present

    - name: start nginx server
      service:
        name: nginx
        state: started
      become: true

    - name: add nginx config file
      copy:
        src: etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        content: "hello welcome to the webpage"


      

