---
- name: create hpmepage and install of software packages  
  hosts: all
  become: true
  vars:
    - MyMessage: "This is a simple webpage hosted on nginx"
  tasks: 
           
    - name: install nginx 
      yum:
        name: 
          - vim
          - nginx
          - git 
        state: present

    - name: start nginx server
      service:
        name: nginx
        state: started
      become: true

    - name: index.html copy
      template:
        src: ./nginx-files/index.html.j2
        dest: /usr/share/nginx/html/index.html


    # - name: create www directory
    #   file:
    #     path: /var
    #     content: "hello welcome to the webpage"


      

