---
- name: create hpmepage and install of software packages  
  hosts: all
  become: true
  vars:
    - myMessage: "This is a simple webpage hosted on nginx"
    - port_num: 8009
  tasks: 
           
    - name: install software packages  
      yum:
        name: 
          - vim
          - nginx
          - git 
        state: present

    - name: start nginx server
      service:
        name: nginx
        state: restarted
      become: true
    
    - name: insert index page into standard nginx dir
      template: 
        src: ./nginx-files/index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: insert conf file is in standard nginx dir
      template:
        src: ./nginx-files/nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: "allow access to port {{ port_num }}"
      firewalld:
        port: "{{ port_num }}/tcp"
        zone: public
        state: enabled

    

      

